# Use the official Python image as the base image
FROM python:3.10-slim

# Set environment variables
# Prevents Python from writing .pyc files to disk
ENV PYTHONDONTWRITEBYTECODE=1  
# Ensures that Python output is sent straight to the terminal without buffering
ENV PYTHONUNBUFFERED=1 

ENV UPLOAD_FOLDER='/upload'

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . /app

# Expose port 5000
EXPOSE 5000

# Command to run the application
CMD ["python", "run.py"]
