# Use the official Python image as the base image
FROM python:3.10-slim AS base

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 
ENV PYTHONUNBUFFERED=1
ENV UPLOAD_FOLDER='/upload'

# Set working directory
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . /app

# Create a non-root user
RUN useradd -m appuser
USER appuser

# Expose port 5000
EXPOSE 5000

# Use gunicorn to run the application in production
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "run:app"]
