name: Docker Image Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-template:
    uses: YajithVishwa/WorkflowTemplate/.github/workflows/publish-github-image.yml@main
    with:
      username: 'yajithvishwa'
      image_name: 'file-server'
    secrets:
      GH_CON_PAT: ${{ secrets.GH_CON_PAT }}
